
CREATE TABLE ACCOUNT
(
 
   ACCOUNTID     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   FIRSTNAME    VARCHAR(20) NOT NULL,
   LASTNAME    VARCHAR(20) NOT NULL,
   CONTACT_EMAIL VARCHAR(20) NOT NULL,
   PAYPALL_EMAIL VARCHAR(20),
   DATEOFBIRTH    VARCHAR(20),
   RESIDENCE       VARCHAR(40),
  
   CONSTRAINT  PK_Account  PRIMARY KEY(ACCOUNTID)
);


CREATE TABLE MoneyTransaction
(

   TRANID     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   CURRENCY_FROM   	VARCHAR(40) NOT NULL,
   CURRENCY_TO     	VARCHAR(10) NOT NULL,
   RATE            	DECIMAL(5,2) ,
   AMOUNT_FROM     	DECIMAL(10,2),
   AMOUNT_TO      	DECIMAL(10,2),
   TRANDATE			VARCHAR(20),
   ACCOUNTID		BIGINT,

   CONSTRAINT  PK_TRAN  PRIMARY KEY(TRANID),
   CONSTRAINT  FK_to_ACCOUNT    FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)

);

CREATE TABLE EXCHANGE_RATE
(
 
   RATEID     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   SYMBOL_FROM    VARCHAR(4) NOT NULL,
   SYMBOL_TO      VARCHAR(4) NOT NULL,
   DATE_OF_TRAN   VARCHAR(20),
   RATE      DECIMAL(10,3),
  
   CONSTRAINT  PK_RATE  PRIMARY KEY(RATEID)
);

